id: P009281
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG18576
  title: བར་སྣང་གི་མགོ་འཁོར་ཕོ་བྲང་།
  author: ''
  volumes:
    4452070e7a9f46aaac8b63fe6a55fa16:
      image_group_id: I1KG18673
      title: ''
      volume_number: 1
      total_pages: 272
      base_file: v001.txt
